---
title: Welcome to the Within Family Consortium
---

The Within Family Consortium is a group of researchers who are interested in using datasets of related individuals to understand how the human genome influences a broad range of medical and socioeconomic traits. Our research involves researchers, expertise and methods from a wide range of fields. We are keen to promote high quality reproducible research. 

## Aims and objectives

1. To undertake within family analyses across all available studies that have sampled related individuals. 
2. Estimate and understand direct and indirect genetic effects 

Direct genetic effects are the effects of inheriting an allele, indirect genetic effects are the effects due to other sources, e.g. demography, population stratification, assortative mating, and genetic nurture from relatives. 

The consortium aims to help undertake projects using datasets of related individuals. Many of these projects require a lot of data, and more samples than are available in any one study. Therefore the best way to conduct these studies is to run analyses in all available studies, that have capacity to contribute. The model we are currently using is to distribute automated scripts and pipelines to studies to minimize the requirement for analyst time at each study, this federated model removes the need to transfer data between institutions and countries. 

## Achievements thus far

We have conducted a within family GWAS using data from 178,086 siblings from 17 cohorts to generate population (between-family) and within-sibship (within-family) estimates of per-locus genetic associations for 25 phenotypes, published Nature Genetics 2022. 

1. Howe, L. J. et al. Within-sibship genome-wide association analyses decrease bias in estimates of direct genetic effects. Nat Genet 54, 581–592 (2022).

## Executive & Steering Committees

We have established Executive & Steering Committees to oversee the development and management of the Within Family Consortium. The Executive Committee comprises:

Neil Davies, Gibran Hemani, David Bann, Ben Brumpton, and Alexandra Havdahl

The Steering Group comprises:

George Davey Smith, Peter Visscher, Per Magnus, Marcus Munafò, Rebecca Pearson, Camilla Stoltenberg, Bjørn Åsvold, David Evans, Sarah Medland, Dan Benjamin, Philipp Koellinger, Melinda Mills, Jonathan Beauchamp, Jaakko Kaprio, Caroline Hayward, Archie Campbell, Andrew McIntosh, Zhengming Chen, Iona  Millwood, Karl Heilbron, Michel Nivard, and Emla Fitzsimons.

## Contact

We welcome any feedback, questions, requests for further information or summary data, or invitations to collaborate. To reach the investigators please email [Neil Davies](mailto:neil.m.davies@ucl.ac.uk). 

## Acknowledgments

The Within Family Consortium is supported by The Medical Research Council (MRC) and the University of Bristol [MC_UU_00011/1], Gib Hemani's Wellcome Trust and Royal Society Henry Dale Fellowship [208806/Z/17/Z] and the National Institute of Mental Health (NIMH) MH130448.
